USE [customer];
GO

SELECT * FROM [dbo].[processed_customer_shopping_behavior (1)];

--Q1. Total revenue generated by male vs. female customers
SELECT gender,SUM(purchase_amount) AS Total_Revenue 
FROM [processed_customer_shopping_behavior (1)]
GROUP BY gender;

--Q2. Customers who used a discount but spent more than average
SELECT customer_id
FROM [processed_customer_shopping_behavior (1)]
WHERE discount_applied='Yes' AND 
	purchase_amount>(SELECT AVG(purchase_amount) FROM [processed_customer_shopping_behavior (1)]);

--Q3. Top 5 products with the highest average review rating
SELECT Top 5 item_purchased,ROUND(AVG(review_rating),2) AS Average_Rating 
FROM [processed_customer_shopping_behavior (1)]
GROUP BY item_purchased
ORDER BY Average_Rating DESC; 

--Q4. Average Purchase Amounts: Standard vs. Express Shipping
SELECT shipping_type,ROUND(AVG(purchase_amount),2) AS AVRAGE_PURCHASE_AMOUNT
FROM [processed_customer_shopping_behavior (1)]
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type; 

--Q5. Subscribed vs. Non-Subscribed: Average Spend and Total Revenue
SELECT subscription_status as Subscription_Status,
COUNT(customer_id) AS Total_Customers,
	AVG(purchase_amount) AS Average_Spend, 
	SUM(purchase_amount) AS Total_Revenue 
    FROM [processed_customer_shopping_behavior (1)]
WHERE subscription_status IN ('Yes','No')
GROUP BY subscription_status;

--Q6. Top 5 Products with highest percentage of discounted purchases
--Q6. Top 5 Products with highest percentage of discounted purchases
SELECT 
    item_purchased,
    ROUND(
        (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0) / COUNT(*),
        2) AS Discount_Percentage
FROM [processed_customer_shopping_behavior (1)]
GROUP BY item_purchased
ORDER BY Discount_Percentage DESC
OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;

--Q7. Segment customers into New, Returning, and Loyal

SELECT Customer_Segment, COUNT(*) AS Number_of_customer
FROM (
    SELECT 
        customer_id,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS Customer_Segment
    FROM [processed_customer_shopping_behavior (1)]
) AS Segmented_Customers
GROUP BY Customer_Segment;

--Q8. Top 3 most purchased products within each category
WITH item_counts AS (
    SELECT category,item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM [processed_customer_shopping_behavior (1)]
    GROUP BY category, item_purchased
)
SELECT item_rank,category,item_purchased,total_orders
FROM item_counts
WHERE item_rank <= 3;

--Q9. Subscription likelihood for Repeat Buyers (>5 purchases)
SELECT subscription_status,COUNT(customer_id) AS repeat_buyers
FROM [processed_customer_shopping_behavior (1)]
WHERE previous_purchases > 5
group by subscription_status;
--Q10. Revenue contribution of each age group
SELECT age_group,SUM(purchase_amount)AS total_revenue
FROM [processed_customer_shopping_behavior (1)]
GROUP BY age_group
ORDER BY total_revenue DESC;